include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_declarations
    - sort_child_properties_last
    - use_key_in_widget_constructors
    - avoid_print
