import '../../data/models/exercise.dart';

/// Complete definitions for all six exercises and their ten progression steps.
/// Data sourced from Paul Wade's Convict Conditioning programme.
const List<Exercise> kAllExercises = [
  _pushUps,
  _squats,
  _pullUps,
  _legRaises,
  _bridges,
  _handstands,
];

Exercise exerciseForType(ExerciseType type) =>
    kAllExercises.firstWhere((e) => e.type == type);

// ─── 伏地挺身 Push-ups ────────────────────────────────────────────────────────

const Exercise _pushUps = Exercise(
  type: ExerciseType.pushUp,
  steps: [
    ExerciseStep(
      stepNumber: 1,
      nameZh: '壁上推',
      nameEn: 'Wall Push-up',
      description: '面向牆壁站立，雙手與肩同寬置於牆上，手臂伸直後彎曲至胸部靠近牆壁，再推回。',
      beginner: StepStandard.reps(sets: 1, reps: 10),
      intermediate: StepStandard.reps(sets: 2, reps: 25),
      progression: StepStandard.reps(sets: 3, reps: 50),
    ),
    ExerciseStep(
      stepNumber: 2,
      nameZh: '傾斜推',
      nameEn: 'Incline Push-up',
      description: '雙手放在高於地面的穩固表面（如桌緣、階梯），身體呈斜線，做標準推地動作。',
      beginner: StepStandard.reps(sets: 1, reps: 10),
      intermediate: StepStandard.reps(sets: 2, reps: 20),
      progression: StepStandard.reps(sets: 3, reps: 40),
    ),
    ExerciseStep(
      stepNumber: 3,
      nameZh: '跪姿推',
      nameEn: 'Kneeling Push-up',
      description: '膝蓋跪地，雙手與肩同寬置於地上，身體呈斜線，做推地動作。膝蓋至頭部保持一直線。',
      beginner: StepStandard.reps(sets: 1, reps: 10),
      intermediate: StepStandard.reps(sets: 2, reps: 15),
      progression: StepStandard.reps(sets: 3, reps: 30),
    ),
    ExerciseStep(
      stepNumber: 4,
      nameZh: '半程推',
      nameEn: 'Half Push-up',
      description: '標準推地姿勢，但只下降至手肘彎曲約90度（半程），再推回。幫助建立上肢力量。',
      beginner: StepStandard.reps(sets: 1, reps: 8),
      intermediate: StepStandard.reps(sets: 2, reps: 12),
      progression: StepStandard.reps(sets: 2, reps: 25),
    ),
    ExerciseStep(
      stepNumber: 5,
      nameZh: '標準推',
      nameEn: 'Full Push-up',
      description: '標準伏地挺身。雙手與肩同寬，身體挺直，胸部下降至幾乎觸地，再完全推起。',
      beginner: StepStandard.reps(sets: 1, reps: 5),
      intermediate: StepStandard.reps(sets: 2, reps: 10),
      progression: StepStandard.reps(sets: 2, reps: 20),
    ),
    ExerciseStep(
      stepNumber: 6,
      nameZh: '窄距推',
      nameEn: 'Close Push-up',
      description: '雙手距離縮短至拇指與食指可相觸，身體下降時手肘緊貼身體兩側。',
      beginner: StepStandard.reps(sets: 1, reps: 5),
      intermediate: StepStandard.reps(sets: 2, reps: 10),
      progression: StepStandard.reps(sets: 2, reps: 20),
    ),
    ExerciseStep(
      stepNumber: 7,
      nameZh: '偏重推',
      nameEn: 'Uneven Push-up',
      description: '一手置於地面，另一手放在籃球或類似物體上，做推地動作。兩側交替訓練。',
      beginner: StepStandard.reps(sets: 1, reps: 5),
      intermediate: StepStandard.reps(sets: 2, reps: 10),
      progression: StepStandard.reps(sets: 2, reps: 20),
    ),
    ExerciseStep(
      stepNumber: 8,
      nameZh: '半單手推',
      nameEn: 'Half One-Arm Push-up',
      description: '單手伏地挺身，但只下降至手肘彎曲約90度。另一手背在身後。兩側交替。',
      beginner: StepStandard.reps(sets: 1, reps: 5),
      intermediate: StepStandard.reps(sets: 2, reps: 10),
      progression: StepStandard.reps(sets: 2, reps: 20),
    ),
    ExerciseStep(
      stepNumber: 9,
      nameZh: '槓桿推',
      nameEn: 'Lever Push-up',
      description: '一手置於地面，另一手完全伸直撐在籃球上，做單手推地動作。兩側交替訓練。',
      beginner: StepStandard.reps(sets: 1, reps: 5),
      intermediate: StepStandard.reps(sets: 2, reps: 8),
      progression: StepStandard.reps(sets: 2, reps: 15),
    ),
    ExerciseStep(
      stepNumber: 10,
      nameZh: '單手推',
      nameEn: 'One-Arm Push-up',
      description: '單手完整伏地挺身：另一手背於身後，雙腳可稍微分開以維持平衡。兩側交替訓練。',
      beginner: StepStandard.reps(sets: 1, reps: 1),
      intermediate: StepStandard.reps(sets: 1, reps: 5),
      progression: StepStandard.reps(sets: 2, reps: 100),
    ),
  ],
);

// ─── 深蹲 Squats ─────────────────────────────────────────────────────────────

const Exercise _squats = Exercise(
  type: ExerciseType.squat,
  steps: [
    ExerciseStep(
      stepNumber: 1,
      nameZh: '肩撐深蹲',
      nameEn: 'Shoulderstand Squat',
      description: '仰臥，雙腿舉至頭頂上方，以肩膀支撐，反覆彎曲及伸直膝蓋。增強腿部柔韌性。',
      beginner: StepStandard.reps(sets: 1, reps: 10),
      intermediate: StepStandard.reps(sets: 2, reps: 25),
      progression: StepStandard.reps(sets: 3, reps: 50),
    ),
    ExerciseStep(
      stepNumber: 2,
      nameZh: '摺刀深蹲',
      nameEn: 'Jackknife Squat',
      description: '站在椅子或床旁，雙手輕輕撐著，做全程深蹲動作。逐步減少對手部的依賴。',
      beginner: StepStandard.reps(sets: 1, reps: 10),
      intermediate: StepStandard.reps(sets: 2, reps: 20),
      progression: StepStandard.reps(sets: 3, reps: 40),
    ),
    ExerciseStep(
      stepNumber: 3,
      nameZh: '支撐深蹲',
      nameEn: 'Supported Squat',
      description: '雙手輕握門框或柱子，做全程深蹲，逐步減少手部支撐力量。',
      beginner: StepStandard.reps(sets: 1, reps: 10),
      intermediate: StepStandard.reps(sets: 2, reps: 15),
      progression: StepStandard.reps(sets: 3, reps: 30),
    ),
    ExerciseStep(
      stepNumber: 4,
      nameZh: '半程深蹲',
      nameEn: 'Half Squat',
      description: '雙腳與肩同寬，只蹲至大腿與地面成45度角（半程），再站回。',
      beginner: StepStandard.reps(sets: 1, reps: 8),
      intermediate: StepStandard.reps(sets: 2, reps: 25),
      progression: StepStandard.reps(sets: 2, reps: 50),
    ),
    ExerciseStep(
      stepNumber: 5,
      nameZh: '標準深蹲',
      nameEn: 'Full Squat',
      description: '標準深蹲：雙腳與肩同寬，腳尖微朝外，蹲至大腿平行地面或更低，脊背挺直。',
      beginner: StepStandard.reps(sets: 1, reps: 5),
      intermediate: StepStandard.reps(sets: 2, reps: 15),
      progression: StepStandard.reps(sets: 2, reps: 30),
    ),
    ExerciseStep(
      stepNumber: 6,
      nameZh: '窄距深蹲',
      nameEn: 'Close Squat',
      description: '雙腳併攏做完整深蹲，增加平衡要求和腿部外側肌群的挑戰。',
      beginner: StepStandard.reps(sets: 1, reps: 5),
      intermediate: StepStandard.reps(sets: 2, reps: 10),
      progression: StepStandard.reps(sets: 2, reps: 20),
    ),
    ExerciseStep(
      stepNumber: 7,
      nameZh: '偏重深蹲',
      nameEn: 'Uneven Squat',
      description: '一腳踩在籃球等物體上，另一腳踩地，以雙腳做深蹲。兩側交替訓練，準備單腿蹲。',
      beginner: StepStandard.reps(sets: 1, reps: 5),
      intermediate: StepStandard.reps(sets: 2, reps: 10),
      progression: StepStandard.reps(sets: 2, reps: 20),
    ),
    ExerciseStep(
      stepNumber: 8,
      nameZh: '半單腿深蹲',
      nameEn: 'Half One-Leg Squat',
      description: '單腳站立（另一腳伸直懸空），只蹲至膝蓋彎曲約90度（半程）。兩側交替。',
      beginner: StepStandard.reps(sets: 1, reps: 5),
      intermediate: StepStandard.reps(sets: 2, reps: 10),
      progression: StepStandard.reps(sets: 2, reps: 20),
    ),
    ExerciseStep(
      stepNumber: 9,
      nameZh: '輔助單腿深蹲',
      nameEn: 'Assisted One-Leg Squat',
      description: '單腳全程深蹲，以一隻手輕輕扶著支撐物，逐步減少依賴。兩側交替訓練。',
      beginner: StepStandard.reps(sets: 1, reps: 5),
      intermediate: StepStandard.reps(sets: 2, reps: 8),
      progression: StepStandard.reps(sets: 2, reps: 15),
    ),
    ExerciseStep(
      stepNumber: 10,
      nameZh: '單腿深蹲',
      nameEn: 'One-Leg Squat',
      description: '完整單腿深蹲（槍式深蹲）：一腳站立，另一腳水平伸直，蹲至最低點再站回。',
      beginner: StepStandard.reps(sets: 1, reps: 1),
      intermediate: StepStandard.reps(sets: 1, reps: 5),
      progression: StepStandard.reps(sets: 2, reps: 50),
    ),
  ],
);

// ─── 引體向上 Pull-ups ────────────────────────────────────────────────────────

const Exercise _pullUps = Exercise(
  type: ExerciseType.pullUp,
  steps: [
    ExerciseStep(
      stepNumber: 1,
      nameZh: '直立拉',
      nameEn: 'Vertical Pull',
      description: '面向門框或固定柱，雙手握住，身體略微後傾，以背部和手臂力量拉動身體。',
      beginner: StepStandard.reps(sets: 1, reps: 10),
      intermediate: StepStandard.reps(sets: 2, reps: 20),
      progression: StepStandard.reps(sets: 3, reps: 40),
    ),
    ExerciseStep(
      stepNumber: 2,
      nameZh: '水平拉',
      nameEn: 'Horizontal Pull',
      description: '使用低槓（腰部高度），雙腳伸直置於地面，身體水平，做划船動作。',
      beginner: StepStandard.reps(sets: 1, reps: 10),
      intermediate: StepStandard.reps(sets: 2, reps: 15),
      progression: StepStandard.reps(sets: 3, reps: 30),
    ),
    ExerciseStep(
      stepNumber: 3,
      nameZh: '摺刀引體',
      nameEn: 'Jackknife Pull',
      description: '站在高槓下方，雙腳踩地，以腿部輔助拉起身體。逐步減少腿部輔助力量。',
      beginner: StepStandard.reps(sets: 1, reps: 10),
      intermediate: StepStandard.reps(sets: 2, reps: 15),
      progression: StepStandard.reps(sets: 3, reps: 20),
    ),
    ExerciseStep(
      stepNumber: 4,
      nameZh: '半程引體',
      nameEn: 'Half Pull-up',
      description: '懸掛於單槓，只拉至手肘彎曲約90度（下半段），再放下。建立懸吊力量。',
      beginner: StepStandard.reps(sets: 1, reps: 8),
      intermediate: StepStandard.reps(sets: 2, reps: 11),
      progression: StepStandard.reps(sets: 2, reps: 15),
    ),
    ExerciseStep(
      stepNumber: 5,
      nameZh: '標準引體',
      nameEn: 'Full Pull-up',
      description: '標準引體向上：從完全懸掛開始，拉至下巴超過槓，再完全放下。',
      beginner: StepStandard.reps(sets: 1, reps: 3),
      intermediate: StepStandard.reps(sets: 2, reps: 6),
      progression: StepStandard.reps(sets: 2, reps: 10),
    ),
    ExerciseStep(
      stepNumber: 6,
      nameZh: '窄距引體',
      nameEn: 'Close Pull-up',
      description: '雙手握距縮至拇指相觸，以窄距做完整引體向上，增加二頭肌和前臂參與度。',
      beginner: StepStandard.reps(sets: 1, reps: 3),
      intermediate: StepStandard.reps(sets: 2, reps: 6),
      progression: StepStandard.reps(sets: 2, reps: 10),
    ),
    ExerciseStep(
      stepNumber: 7,
      nameZh: '偏重引體',
      nameEn: 'Uneven Pull-up',
      description: '一手握槓，另一手握毛巾或繩子，做引體向上。逐步加重主力手的負荷。兩側交替。',
      beginner: StepStandard.reps(sets: 1, reps: 3),
      intermediate: StepStandard.reps(sets: 2, reps: 5),
      progression: StepStandard.reps(sets: 2, reps: 9),
    ),
    ExerciseStep(
      stepNumber: 8,
      nameZh: '半單手引體',
      nameEn: 'Half One-Arm Pull-up',
      description: '一手握槓，另一手握同側手腕輔助，做引體向上。手腕輔助力量逐漸減少。兩側交替。',
      beginner: StepStandard.reps(sets: 1, reps: 3),
      intermediate: StepStandard.reps(sets: 2, reps: 4),
      progression: StepStandard.reps(sets: 2, reps: 8),
    ),
    ExerciseStep(
      stepNumber: 9,
      nameZh: '輔助單手引體',
      nameEn: 'Assisted One-Arm Pull-up',
      description: '一手握槓做引體，另一手輕搭在毛巾上提供極少量輔助。兩側交替訓練。',
      beginner: StepStandard.reps(sets: 1, reps: 2),
      intermediate: StepStandard.reps(sets: 2, reps: 3),
      progression: StepStandard.reps(sets: 2, reps: 6),
    ),
    ExerciseStep(
      stepNumber: 10,
      nameZh: '單手引體',
      nameEn: 'One-Arm Pull-up',
      description: '完整單手引體向上：一手握槓，另一手自然垂下或輕握手腕，從懸掛拉至下巴過槓。',
      beginner: StepStandard.reps(sets: 1, reps: 1),
      intermediate: StepStandard.reps(sets: 1, reps: 3),
      progression: StepStandard.reps(sets: 2, reps: 6),
    ),
  ],
);

// ─── 舉腿 Leg Raises ─────────────────────────────────────────────────────────

const Exercise _legRaises = Exercise(
  type: ExerciseType.legRaise,
  steps: [
    ExerciseStep(
      stepNumber: 1,
      nameZh: '抱膝',
      nameEn: 'Knee Tuck',
      description: '坐在椅子邊緣，雙手撐側面，反覆將雙膝收向胸口再放下，訓練腹肌啟動。',
      beginner: StepStandard.reps(sets: 1, reps: 10),
      intermediate: StepStandard.reps(sets: 2, reps: 25),
      progression: StepStandard.reps(sets: 3, reps: 40),
    ),
    ExerciseStep(
      stepNumber: 2,
      nameZh: '臥姿舉膝',
      nameEn: 'Flat Knee Raise',
      description: '仰臥，雙手置於身側，反覆將膝蓋抬向胸口再放回。感受腹肌全程收縮。',
      beginner: StepStandard.reps(sets: 1, reps: 10),
      intermediate: StepStandard.reps(sets: 2, reps: 20),
      progression: StepStandard.reps(sets: 3, reps: 35),
    ),
    ExerciseStep(
      stepNumber: 3,
      nameZh: '臥姿屈腿舉',
      nameEn: 'Flat Bent Leg Raise',
      description: '仰臥，膝蓋略彎，從地面將雙腿舉至垂直地面，再緩慢放下，感受腹肌下部。',
      beginner: StepStandard.reps(sets: 1, reps: 10),
      intermediate: StepStandard.reps(sets: 2, reps: 15),
      progression: StepStandard.reps(sets: 3, reps: 30),
    ),
    ExerciseStep(
      stepNumber: 4,
      nameZh: '臥姿蛙式舉',
      nameEn: 'Flat Frog Raise',
      description: '仰臥，膝蓋向外展開如青蛙腳，用此姿勢將腿舉至垂直地面，再放下。',
      beginner: StepStandard.reps(sets: 1, reps: 8),
      intermediate: StepStandard.reps(sets: 2, reps: 15),
      progression: StepStandard.reps(sets: 2, reps: 25),
    ),
    ExerciseStep(
      stepNumber: 5,
      nameZh: '臥姿直腿舉',
      nameEn: 'Flat Straight Leg Raise',
      description: '仰臥，雙腿完全伸直，從地面舉至垂直地面，再緩慢放下（不落地）。',
      beginner: StepStandard.reps(sets: 1, reps: 5),
      intermediate: StepStandard.reps(sets: 2, reps: 10),
      progression: StepStandard.reps(sets: 2, reps: 20),
    ),
    ExerciseStep(
      stepNumber: 6,
      nameZh: '懸吊舉膝',
      nameEn: 'Hanging Knee Raise',
      description: '懸掛於單槓，反覆將膝蓋收向胸口，保持核心穩定，避免身體搖晃。',
      beginner: StepStandard.reps(sets: 1, reps: 5),
      intermediate: StepStandard.reps(sets: 2, reps: 10),
      progression: StepStandard.reps(sets: 2, reps: 15),
    ),
    ExerciseStep(
      stepNumber: 7,
      nameZh: '懸吊屈腿舉',
      nameEn: 'Hanging Bent Leg Raise',
      description: '懸掛於槓，膝蓋微彎，將雙腿舉至腰部以上高度，再慢慢放下。',
      beginner: StepStandard.reps(sets: 1, reps: 5),
      intermediate: StepStandard.reps(sets: 2, reps: 10),
      progression: StepStandard.reps(sets: 2, reps: 15),
    ),
    ExerciseStep(
      stepNumber: 8,
      nameZh: '懸吊蛙式舉',
      nameEn: 'Hanging Frog Raise',
      description: '懸掛於槓，以蛙式（膝蓋外展）將腿舉至腹部高度，訓練髖屈肌和腹肌。',
      beginner: StepStandard.reps(sets: 1, reps: 5),
      intermediate: StepStandard.reps(sets: 2, reps: 8),
      progression: StepStandard.reps(sets: 2, reps: 15),
    ),
    ExerciseStep(
      stepNumber: 9,
      nameZh: '半程直腿舉',
      nameEn: 'Partial Straight Leg Raise',
      description: '懸掛於槓，雙腿伸直，舉至與地面平行（90度）的位置，再放下。',
      beginner: StepStandard.reps(sets: 1, reps: 5),
      intermediate: StepStandard.reps(sets: 2, reps: 8),
      progression: StepStandard.reps(sets: 2, reps: 15),
    ),
    ExerciseStep(
      stepNumber: 10,
      nameZh: '直腿舉',
      nameEn: 'Straight Leg Raise',
      description: '懸掛於槓，雙腿完全伸直，舉至腳尖觸槓（垂直），再慢慢放下。終極腹肌挑戰。',
      beginner: StepStandard.reps(sets: 1, reps: 1),
      intermediate: StepStandard.reps(sets: 1, reps: 5),
      progression: StepStandard.reps(sets: 2, reps: 30),
    ),
  ],
);

// ─── 橋式 Bridges ─────────────────────────────────────────────────────────────

const Exercise _bridges = Exercise(
  type: ExerciseType.bridge,
  steps: [
    ExerciseStep(
      stepNumber: 1,
      nameZh: '短橋',
      nameEn: 'Short Bridge',
      description: '仰臥，膝蓋彎曲，腳平放地面，將臀部抬起至大腿與身體成直線，保持頂點再放下。',
      beginner: StepStandard.reps(sets: 1, reps: 10),
      intermediate: StepStandard.reps(sets: 2, reps: 25),
      progression: StepStandard.reps(sets: 3, reps: 50),
    ),
    ExerciseStep(
      stepNumber: 2,
      nameZh: '直橋',
      nameEn: 'Straight Bridge',
      description: '坐姿，雙腳伸直，雙手置於臀部後方，推起臀部使身體成一直線，反覆進行。',
      beginner: StepStandard.reps(sets: 1, reps: 10),
      intermediate: StepStandard.reps(sets: 2, reps: 20),
      progression: StepStandard.reps(sets: 3, reps: 40),
    ),
    ExerciseStep(
      stepNumber: 3,
      nameZh: '斜橋',
      nameEn: 'Angled Bridge',
      description: '仰臥，將腳放在較高平面（如椅子），雙手放在地面，推起臀部形成斜橋。',
      beginner: StepStandard.reps(sets: 1, reps: 10),
      intermediate: StepStandard.reps(sets: 2, reps: 15),
      progression: StepStandard.reps(sets: 3, reps: 30),
    ),
    ExerciseStep(
      stepNumber: 4,
      nameZh: '頭頂橋',
      nameEn: 'Head Bridge',
      description: '仰臥，膝蓋彎曲，以頭頂和腳支撐拱起身體，手臂交叉置於胸前。',
      beginner: StepStandard.reps(sets: 1, reps: 8),
      intermediate: StepStandard.reps(sets: 2, reps: 15),
      progression: StepStandard.reps(sets: 2, reps: 25),
    ),
    ExerciseStep(
      stepNumber: 5,
      nameZh: '半橋',
      nameEn: 'Half Bridge',
      description: '仰臥，雙手置於頭旁，推起身體至手臂伸直，但只達到半程高度，再放下。',
      beginner: StepStandard.reps(sets: 1, reps: 5),
      intermediate: StepStandard.reps(sets: 2, reps: 10),
      progression: StepStandard.reps(sets: 2, reps: 20),
    ),
    ExerciseStep(
      stepNumber: 6,
      nameZh: '標準橋',
      nameEn: 'Full Bridge',
      description: '仰臥，雙手置於頭旁，完全推起身體形成弓橋，手臂伸直，頭部離地，再放下。',
      beginner: StepStandard.reps(sets: 1, reps: 3),
      intermediate: StepStandard.reps(sets: 2, reps: 8),
      progression: StepStandard.reps(sets: 2, reps: 15),
    ),
    ExerciseStep(
      stepNumber: 7,
      nameZh: '靠牆下橋',
      nameEn: 'Wall Walking Down',
      description: '站在牆前，背對牆，身體後仰，雙手沿牆向下移動至橋式姿勢，再走回站立。',
      beginner: StepStandard.reps(sets: 1, reps: 3),
      intermediate: StepStandard.reps(sets: 2, reps: 8),
      progression: StepStandard.reps(sets: 2, reps: 15),
    ),
    ExerciseStep(
      stepNumber: 8,
      nameZh: '靠牆上橋',
      nameEn: 'Wall Walking Up',
      description: '從地面橋式開始，以雙手沿牆向上移動至站立姿勢（反向），訓練後彎力量。',
      beginner: StepStandard.reps(sets: 1, reps: 3),
      intermediate: StepStandard.reps(sets: 2, reps: 6),
      progression: StepStandard.reps(sets: 2, reps: 10),
    ),
    ExerciseStep(
      stepNumber: 9,
      nameZh: '閉合橋',
      nameEn: 'Closing Bridge',
      description: '從站立下橋後，再站回，全程不靠牆輔助，由站立直接下橋再回到站立。',
      beginner: StepStandard.reps(sets: 1, reps: 1),
      intermediate: StepStandard.reps(sets: 2, reps: 3),
      progression: StepStandard.reps(sets: 2, reps: 6),
    ),
    ExerciseStep(
      stepNumber: 10,
      nameZh: '站立橋',
      nameEn: 'Stand-to-Stand Bridge',
      description: '從站立直接後彎至橋式，再推起回到站立，全程流暢完成。脊椎終極柔韌訓練。',
      beginner: StepStandard.reps(sets: 1, reps: 1),
      intermediate: StepStandard.reps(sets: 1, reps: 3),
      progression: StepStandard.reps(sets: 2, reps: 30),
    ),
  ],
);

// ─── 倒立推 Handstand Push-ups ────────────────────────────────────────────────

const Exercise _handstands = Exercise(
  type: ExerciseType.handstand,
  steps: [
    ExerciseStep(
      stepNumber: 1,
      nameZh: '靠牆頭頂',
      nameEn: 'Wall Headstand',
      description: '靠牆做頭手倒立（三點倒立），保持靜止，訓練頸部、肩部力量與平衡感。',
      beginner: StepStandard.hold(sets: 1, holdSeconds: 30),
      intermediate: StepStandard.hold(sets: 2, holdSeconds: 60),
      progression: StepStandard.hold(sets: 2, holdSeconds: 120),
    ),
    ExerciseStep(
      stepNumber: 2,
      nameZh: '烏鴉式',
      nameEn: 'Crow Stand',
      description: '雙手撐地，膝蓋靠在手臂上，前傾使雙腳離地，保持平衡。訓練手腕和核心。',
      beginner: StepStandard.hold(sets: 1, holdSeconds: 10),
      intermediate: StepStandard.hold(sets: 2, holdSeconds: 30),
      progression: StepStandard.hold(sets: 2, holdSeconds: 60),
    ),
    ExerciseStep(
      stepNumber: 3,
      nameZh: '靠牆倒立',
      nameEn: 'Wall Handstand',
      description: '靠牆手倒立，雙手撐地，腳跟靠牆，保持身體垂直。訓練肩部和核心穩定性。',
      beginner: StepStandard.hold(sets: 1, holdSeconds: 30),
      intermediate: StepStandard.hold(sets: 2, holdSeconds: 60),
      progression: StepStandard.hold(sets: 2, holdSeconds: 120),
    ),
    ExerciseStep(
      stepNumber: 4,
      nameZh: '半程倒立推',
      nameEn: 'Half Handstand Push-up',
      description: '靠牆倒立，只將頭部下降至手肘彎曲約90度（半程），再推回。',
      beginner: StepStandard.reps(sets: 1, reps: 5),
      intermediate: StepStandard.reps(sets: 2, reps: 10),
      progression: StepStandard.reps(sets: 2, reps: 20),
    ),
    ExerciseStep(
      stepNumber: 5,
      nameZh: '標準倒立推',
      nameEn: 'Handstand Push-up',
      description: '靠牆倒立，完全下降至頭頂輕觸地面，再完全推起。全程肩部、三頭肌發力。',
      beginner: StepStandard.reps(sets: 1, reps: 2),
      intermediate: StepStandard.reps(sets: 2, reps: 7),
      progression: StepStandard.reps(sets: 2, reps: 15),
    ),
    ExerciseStep(
      stepNumber: 6,
      nameZh: '窄距倒立推',
      nameEn: 'Close Handstand Push-up',
      description: '靠牆倒立，雙手間距縮短至拇指相觸，做完整倒立推。',
      beginner: StepStandard.reps(sets: 1, reps: 2),
      intermediate: StepStandard.reps(sets: 2, reps: 6),
      progression: StepStandard.reps(sets: 2, reps: 12),
    ),
    ExerciseStep(
      stepNumber: 7,
      nameZh: '偏重倒立推',
      nameEn: 'Uneven Handstand Push-up',
      description: '靠牆倒立，一手置於地面，另一手置於較低支撐物，做倒立推。兩側交替。',
      beginner: StepStandard.reps(sets: 1, reps: 1),
      intermediate: StepStandard.reps(sets: 2, reps: 5),
      progression: StepStandard.reps(sets: 2, reps: 10),
    ),
    ExerciseStep(
      stepNumber: 8,
      nameZh: '半單手倒立推',
      nameEn: 'Half One-Arm HSPU',
      description: '靠牆倒立，一手撐地，另一手放背後，只下降半程後推回。兩側交替訓練。',
      beginner: StepStandard.reps(sets: 1, reps: 1),
      intermediate: StepStandard.reps(sets: 2, reps: 4),
      progression: StepStandard.reps(sets: 2, reps: 8),
    ),
    ExerciseStep(
      stepNumber: 9,
      nameZh: '槓桿倒立推',
      nameEn: 'Lever Handstand Push-up',
      description: '靠牆倒立，一手撐地，另一手輕搭在低支撐物上僅提供極少輔助，做倒立推。',
      beginner: StepStandard.reps(sets: 1, reps: 1),
      intermediate: StepStandard.reps(sets: 2, reps: 3),
      progression: StepStandard.reps(sets: 2, reps: 5),
    ),
    ExerciseStep(
      stepNumber: 10,
      nameZh: '單手倒立推',
      nameEn: 'One-Arm Handstand Push-up',
      description: '完整單手倒立推：靠牆倒立，單手完成完整下降及推起，另一手放背後。',
      beginner: StepStandard.reps(sets: 1, reps: 1),
      intermediate: StepStandard.reps(sets: 1, reps: 2),
      progression: StepStandard.reps(sets: 1, reps: 5),
    ),
  ],
);
